### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by santacrab2** [santacrab2/PKHeXMAUI#4]
- [x] Fix Batch editor empty box crash
- [x] fix hypertraining checkboxes
- [x] fix gender button from switching when pokemon is genderless
- [x] only wipe pk info if not of the same evolution line
- [x] update to latest pkhex commit and match latest reworks
- [x] update alm 
- [x] check manaphy egg after updates 
- [x] tm held items not displaying properly
- [x] examine batch editor things probably changed with latest pkhex
- [x] basic livehex gui?
- [x] add all the rest of the pkhex settings
- [x] start on block editors
